config/routes.rb
Crimedata::Application.routes.draw do
  resources :crimes

  root :to => 'crimes#index'

end

app/models/crime.rb
class Crime < ActiveRecord::Base

  def self.json_converion_for_maps crime_type_array_main, crime_data, type
    crime_type_array = []
    crime = {}
    crime_type_array_main.each_with_index do |crime_type, index|
      crime_type_array[index] = crime_data.select{|key, val| key[type] == crime_type}
      temp_arr = '['
      crime_type_array[index].each_with_index do |crime, ind|
        temp_arr = temp_arr + '{'
        description = '"description":"'
        latitude = ""
        longitude = ""
        title = ""
        crime.each do |key, val|
          if key == 'latitude'
            latitude =  '"lat":' + "'#{val}'" + ','
          elsif key == 'longitude'
            longitude = '"lng":' + "'#{val}'" + ','
          elsif key == 'case_number'
            title = '"title":' + "'#{val}'" + ','
          elsif key != 'location'
            description = description + "#{key}" + ':' + " #{val} --- "
          end
        end
        temp_arr = temp_arr + latitude + longitude + title + description + '"},'
      end
      crime_type_array[index] = temp_arr + ']'
      crime[crime_type] = temp_arr + ']'
    end
    [crime, crime_type_array]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/crimes_controller.rb
require 'rest_client'

class CrimesController < ApplicationController
  # GET /crimes
  # GET /crimes.json
  def index
    @crimes = Crime.all

    crime_data_from_api = RestClient.get 'http://data.cityofchicago.org/resource/ijzp-q8t2.json'
    @crime_data = JSON.parse(crime_data_from_api)

    @crime_type = @crime_data.map{|crime| crime['primary_type']}.uniq
    @crime_year = @crime_data.map{|crime| crime['year']}.uniq
    result = Crime.json_converion_for_maps @crime_type, @crime_data, 'primary_type'
    @crime = result[0]
    @crime_type_array = result[1]

    result_by_year = Crime.json_converion_for_maps @crime_year, @crime_data, 'year'
    @crime_by_year = result_by_year[0]
    @crime_by_year_array = result_by_year[1]

    respond_to do |format|
      format.html # index-old.html.erb
      format.json { render json: @crimes }
    end
  end

  # GET /crimes/1
  # GET /crimes/1.json
  def show
    @crime = Crime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crime }
    end
  end

  # GET /crimes/new
  # GET /crimes/new.json
  def new
    @crime = Crime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crime }
    end
  end

  # GET /crimes/1/edit
  def edit
    @crime = Crime.find(params[:id])
  end

  # POST /crimes
  # POST /crimes.json
  def create
    @crime = Crime.new(params[:crime])

    respond_to do |format|
      if @crime.save
        format.html { redirect_to @crime, notice: 'Crime was successfully created.' }
        format.json { render json: @crime, status: :created, location: @crime }
      else
        format.html { render action: "new" }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crimes/1
  # PUT /crimes/1.json
  def update
    @crime = Crime.find(params[:id])

    respond_to do |format|
      if @crime.update_attributes(params[:crime])
        format.html { redirect_to @crime, notice: 'Crime was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crimes/1
  # DELETE /crimes/1.json
  def destroy
    @crime = Crime.find(params[:id])
    @crime.destroy

    respond_to do |format|
      format.html { redirect_to crimes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/views/crimes/_form.html.erb
<%= form_for(@crime) do |f| %>
  <% if @crime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crime.errors.count, "error") %> prohibited this crime from being saved:</h2>

      <ul>
      <% @crime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crimes/edit.html.erb
<h1>Editing crime</h1>

<%= render 'form' %>

<%= link_to 'Show', @crime %> |
<%= link_to 'Back', crimes_path %>

app/views/crimes/index.html.erb
<%= stylesheet_link_tag 'gmaps4rails' %>
<h1>Crimes</h1>
<div class="dropdown-div">
    <h4>Filter by CRIME TYPE or YEAR</h4>
    <%= select_tag :crime_type, options_for_select(@crime_type) %>
    <%= select_tag :crime_year, options_for_select(@crime_year) %>
</div>
<div id='maps' class="maps">
    <%= gmaps("markers" => { "data" => @crime[@crime_type.first]}, "map_options" => {"auto_adjust" => true }) %>
</div>

<%= yield :scripts %>
<div class="dropdown-div" style="width: 10%;">
    <%= link_to 'Get New Data', { controller: 'crimes', action: 'index'} , id: 'data', class: 'btn-link' %>
</div>
<script type="text/javascript">
  var crime = <%= raw(@crime.to_json.html_safe) %>
  var crime_by_year = <%= raw(@crime_by_year.to_json.html_safe) %>
  $("#crime_type").change(function () {
    var txt = $(this).val();
    Gmaps.map.replaceMarkers(eval(crime[txt]));
  });
  $("#crime_year").change(function () {
    var txt = $(this).val();
    Gmaps.map.replaceMarkers(eval(crime_by_year[txt]));
  });
</script>

<div class="loader"></div>

app/views/crimes/new.html.erb
<h1>New crime</h1>

<%= render 'form' %>

<%= link_to 'Back', crimes_path %>

app/views/crimes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_crime_path(@crime) %> |
<%= link_to 'Back', crimes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crimedata</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>